version: "3.8"

services:
  web:
    build: .
    container_name: ganinew-dev
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev