version: "3.8"

services:
  ganinew-app:
    build: .
    container_name: ganinew-app
    restart: always
    env_file: .env
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--dns-result-order=ipv4first
    ports:
      - "3000:3000"
    command: npm run start
    dns:
      - 8.8.8.8
      - 1.1.1.1
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
